# These jobs test the code and build the wheels and docs.

jobs:
- job: 'manylinux2010'
  condition: eq(variables['build_check'], 'true')
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        arch: x86_64
        plat: manylinux2010_x86_64
        python_ver: '36'
        python.version: '3.6'
      Python37:
        arch: x86_64
        plat: manylinux2010_x86_64
        python_ver: '37'
        python.version: '3.7'
      Python38:
        arch: x86_64
        plat: manylinux2010_x86_64
        python_ver: '38'
        python.version: '3.8'
      Python39:
        arch: x86_64
        plat: manylinux2010_x86_64
        python_ver: '39'
        python.version: '3.9'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - task: Bash@3
    inputs:
      filePath: .azure-ci/build_manylinux2010.sh
    env:
      python_ver: $(python_ver)
    displayName: 'Run the docker, install and uninstall dev environment, test with pytest and flake8, build the wheels'

  - script: |
      set -e
      python -m pip install --upgrade pip
      python -m pip install dist/*manylinux2010*.whl
    displayName: 'Install the wheels'

  - script: |
      set -e
      python -m pip install pytest pytest-cov pytest-timeout pytest-azurepipelines pytest-benchmark flake8 hypothesis
      mkdir tmp_test_cov
      cd tmp_test_cov
      python -m pyflagser.tests --webdl --no-cov --no-coverage-upload
    condition: eq(variables['test_wheels'], 'true')
    displayName: 'Test the wheels with pytest'

  - task: CopyFiles@2
    displayName: 'Copy files'
    inputs:
      contents: 'dist/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Create download link'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'wheel_and_doc'


- job: 'macOS1014'
  condition: eq(variables['build_check'], 'true')
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
      Python39:
        python.version: '3.9'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: |
      set -e
      python -m pip install --upgrade pip setuptools
      python -m pip install wheel
      python -m pip install -e ".[tests, doc]"
    displayName: 'Install dependencies and dev environment'

  - script: |
      flake8
    failOnStderr: true
    displayName: 'Run flake8'

  - script: |
      set -e
      pytest --cov pyflagser --cov-report xml
    displayName: 'Test dev install with pytest'

  - script: |
      python -m pip uninstall -y pyflagser
    failOnStderr: true
    displayName: 'Uninstall pyflagser dev'

  - script: |
      set -e
      python setup.py bdist_wheel
    displayName: 'Build the wheels'

  - script: |
      set -e
      python -m pip install twine
      twine check dist/*
    displayName: 'Check distribution with twine'

  - script: |
      set -e
      python -m pip install dist/*.whl
    displayName: 'Install the wheels'

  - script: |
      set -e
      mkdir tmp_test_cov
      cd tmp_test_cov
      python -m pyflagser.tests --webdl --no-cov --no-coverage-upload
    condition: eq(variables['test_wheels'], 'true')
    displayName: 'Test the wheels with pytest'

  - script: |
      cd doc/
      make html
    failOnStderr: true
    displayName: 'Build sphinx doc'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: doc/build
      includeRootFolder: true
      archiveType: 'zip'
      tarCompression: 'gz'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
    displayName: 'Archive doc'

  - task: CopyFiles@2
    displayName: 'Copy files'
    inputs:
      contents: 'dist/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Create download link'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'wheel_and_doc'


- job: 'win2016'
  condition: eq(variables['build_check'], 'true')
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python36:
        python_ver: '36'
        python.version: '3.6'
      Python37:
        python_ver: '37'
        python.version: '3.7'
      Python38:
        python_ver: '38'
        python.version: '3.8'
      Python39:
        python_ver: '39'
        python.version: '3.9'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: |
      set -e
      python -m pip install --upgrade pip setuptools
      python -m pip install wheel
      python -m pip install -e ".[tests, doc]"
    displayName: 'Install dependencies and dev environment'

  - script: |
      set -e
      pytest pyflagser --no-cov --no-coverage-upload
    displayName: 'Test dev install with pytest'

  - script: |
      pip uninstall -y pyflagser
    failOnStderr: true
    displayName: 'Uninstall pyflagser dev'

  - bash: |
      set -e
      sed -i $'s/\r$//' README.rst
      python setup.py bdist_wheel
    displayName: 'Build the wheels'

  - bash: |
      set -e
      python -m pip install dist/*.whl
    displayName: 'Install the wheels'

  - script: |
      set -e
      mkdir tmp_test_cov
      cd tmp_test_cov
      python -m pyflagser.tests --webdl --no-cov --no-coverage-upload
    condition: eq(variables['test_wheels'], 'true')
    displayName: 'Test the wheels with pytest'

  - task: CopyFiles@2
    displayName: 'Copy files'
    inputs:
      contents: 'dist/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Create download link'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'wheel_and_doc'
