name: Build package on different Os and Python versions

on : [push, pull_request]

jobs:

  build_package:
    name: Build ${{ github.event.repository.name }} on ${{ matrix.os }} for Python-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python-${{ matrix.python-version }} 
        with:
          python-version: ${{ matrix.python-version }}

      - name: Activating Python cache
        uses: actions/cache@v2
        id: cache_python
        continue-on-error: true
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          # The --upgrade and --upgrade-strategy eager flags ensure that pip will always install the latest allowed version of all the dependencies.
          python -m pip install --upgrade --upgrade-strategy eager -r requirements.txt

      - name: Build ${{ github.event.repository.name }}
        run: |
          python -m pip install -e ".[doc, tests]"

      - name: Run test
        run: |
          python -m pip install pytest 
          python -m pytest --no-cov --no-coverage-upload
